version: '3'

volumes:

  yms-pg-data: {}
  yms-rabbitmq-data: {}

services:

  postgres:
    image: sameersbn/postgresql:10-1
    restart: always
    environment:
      DB_NAME: carteiradigital
      DB_USER: postgres
      DB_PASS: postgres
      PG_PASSWORD: postgres
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.7.7-management
    volumes:
      - yms-rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
